### ISSUE TITLE
Bug with 'further results' when template uses 'named args'

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#481]
I have a semantic query that uses a template with 'named args' as its result format. When a user clicks on 'further results', the results are malformed, containing no link to the original pages. Going to 'Edit query' reveals that for reasons unknown to me, the parameter "|?#=Page" ("Page" being the name used for the template) has been changed into "?=Page#-". 

MW 1.22.7/ SMW 1.9.2 (SB)

**Comment by Contrafibularity** [comment]
The method prescribed by http://www.semantic-mediawiki.org/wiki/Help:Template_format is to use

   | ?#=somenameuse

However, this should now work as well

   |mainlabel=-
   | ?=somenameuse

so adding # after ? is no longer necessary it seems (since what version of SMW I don't know). Better still, it is not affected by the issue I raised earlier, or at least it wasn't when I tried this approach.

**Comment by mwjames** [comment]
I think the issue can be resolved by changing `PrintRequest::getSerialisation` with:

```
-				if ( $this->m_outputformat !== '' ) {
+				if ( $this->m_outputformat !== '' && $this->m_label === '' ) {
```

**Comment by mwjames** [comment]
@kghbln Sorry to impeded on your time, could we verify this is still an issue with the reworked list/template format and if it isn't close this one. In case it is still an issue we should have a sandbox case and if we don't close it as well.

**Comment by kghbln** [comment]
The behaviour is unchanged: https://sandbox.semantic-mediawiki.org/wiki/Issue/481 (variant a)
